### ISSUE TITLE
Reported value units

### ISSUE THREAD

**Issue by mhsamavatian** [Aayush-Ankit/dpe_emulate#16]
Can you provide the units for each reported value:

leakage_power: 633.54611067 
node_area: 99.4071733152
leakage_energy: 2.06721891623e-05
tile_area: 0.443768888781
core_area: 0.0296594732947
dynamic_energy: 4.72800337861e-05
total_energy: 6.79522229484e-05
average_power: 960.686284315
time: 7.0733e-05
cycles: 70733
peak_power: 9551.59416329
network packet injection rate: 0.000274674783037
number of tiles mapped: 23

**Comment by pliniosilveira** [comment]
I know from @Aayush-Ankit that:
Power, Energy, and Area are in mW, J, and mm2 respectively.

Time is in seconds.
