### ISSUE TITLE
Data Memory value dictionary

### ISSUE THREAD

**Issue by FrankWu1998** [Aayush-Ankit/dpe_emulate#48]
Hello, can you tell me how to set the specific value of the position of these question marks.

dataMem_lat_dict = {'256' : 1,
                    '512' : 1,
                    '1024': 1,
                    '2048': 1,
		            '4096': ?,  # set
                    '8192': ?}

dataMem_pow_dyn_dict = {'256' : 0.16,
                        '512' : 0.24,
                        '1024': 0.33,
                        '2048': 0.57,
			            '4096': ?,  # set
                        '8192': ?}

dataMem_pow_leak_dict = {'256' : 0.044,
                         '512' : 0.078,
                         '1024': 0.147,
                         '2048': 0.33,
			             '4096': ?,  # set
                         '8192': ?}

dataMem_area_dict = {'256' : 0.00056,
                     '512' : 0.00108,
                     '1024': 0.00192,
                     '2048': 0.00392,
		             '4096': ?,  # set
                     '8192': ?}

dataMem_lat_dict = {'256' : 1,
                    '512' : 1,
                    '1024': 1,
                    '2048': 1,
		            '4096': ?,
                    '8192': ?}

dataMem_pow_dyn_dict = {'256' : 0.16,
                        '512' : 0.24,
                        '1024': 0.33,
                        '2048': 0.57,
			            '4096': ?,
                        '8192': ?}

dataMem_pow_leak_dict = {'256' : 0.044,
                         '512' : 0.078,
                         '1024': 0.147,
                         '2048': 0.33,
			             '4096': ?,  # set
                         '8192': ?}

dataMem_area_dict = {'256' : 0.00056,
                     '512' : 0.00108,
                     '1024': 0.00192,
                     '2048': 0.00392,
		             '4096': ?,  # set
                     '8192': ?}

**Comment by negishubham** [comment]
Hi @FrankWu1998,

The keys that have their values currently are reported using the CACTI tool. In subsequent PR some other keys are included as well.

Thanks,
Shubham

**Comment by FrankWu1998** [comment]
@negishubham Thank you very much.

**Comment by FrankWu1998** [comment]
Hello! @negishubham 
I cannot know the hardware parameters of the memory module other than the size, which makes me unable to directly model the memory module. Can you provide a .cfg file describing eDRAM in CATTI?

best regards,
Yifan Wu

**Comment by FrankWu1998** [comment]
# Note the read and write lat/pow are for entire xbar
xbar_rd_lat = 328.0 * 1000 * (1/32.0)
xbar_wr_lat = 351.0 * 1000 * (1/32.0)

Hello, is the above 32.0 equal to cfg.xbar_ size？
cfg.xbar_size = 32 --> xbar_wr_lat = 351.0 * 1000 * (1/32.0) ?
cfg.xbar_size = 128 --> xbar_wr_lat = 351.0 * 1000 * (1/128.0) ?
