### ISSUE TITLE
python2 dpe.py -n lstm

### ISSUE THREAD

**Issue by 903644485** [Aayush-Ankit/dpe_emulate#6]
请问一下执行python2 dpe.py -n lstm的时候会报错，说IOError: [Errno 2] No such file or directory: '/home/sjtuca/puma/puma-simulator/test/testasm/lstm/tile0/tile_imem.npy'.请问这是怎么回事，也找不到25个tile。assert那句话不注释掉会报错，但产生25个tile目录的命令被注释掉了。请问这里是怎么操作的？

**Comment by Aayush-Ankit** [comment]
Do you have the ``lstm`` directory in the <>/puma-simulator/test/testasm/ ?
There was a bug in Step 6.2 earlier: ``cp -R large ...`` should be ``cp -R <created-folder-after-generate> ...``.

**Comment by Aayush-Ankit** [comment]
For reference: the folder structure of generated-folder (i.e. ``lstm``) for lstm-layer.cpp benchmark should be similar to the figure below:

![bug_fix](https://user-images.githubusercontent.com/6436619/65260146-e8c9ba80-dad3-11e9-8e43-2b4706188b01.png)
